ty=window.ty||{};ty.account=ty.account||{};ty.account.onLoginRedirection=function(resp){resp=$.parseJSON(resp);if(resp.success){if(ty.fwdURL!=""){window.location.replace(ty.fwdURL);}else{window.location.replace(window.location.host);}}else{ty.utils.showStickyNotification(resp.error.message);}}
ty.account.onFBGPlusLogin=function(resp){resp=$.parseJSON(resp);if(resp.success){$('.account-dialog').qtip('hide');$('#authInfoLinks .logged-in').show();$('#authInfoLinks .logged-out').hide();ty.utils.showStickyNotification(resp.data.message);}else{$('.account-dialog').qtip('hide');ty.utils.showStickyNotification(resp.error.message);}};ty.account.Auth=function(){init();function init(){initLogin();initRegister();}
function initLogin(){var $loginMarkupEl=$('#loginContent');var loginMarkup=$loginMarkupEl.html();var $forgotPasswordMarkupEl=$('#forgotPasswordContent');var forgotPasswordMarkup=$forgotPasswordMarkupEl.html();$loginMarkupEl.remove();$forgotPasswordMarkupEl.remove();var markup='<div id="loginContent">'+loginMarkup+'</div>';markup+='<div id="forgotPasswordContent" style="display:none">'+forgotPasswordMarkup+'</div>';var $linkEl=$('#loginBtn');$linkEl.click(function(){showDialog(markup,cbLoginRender);});}
function initRegister(){var $registerMarkupEl=$('#registerContent');var registerMarkup=$registerMarkupEl.html();$registerMarkupEl.remove();var markup='<div id="registerContent">'+registerMarkup+'</div>';var $linkEl=$('#registerBtn');$linkEl.click(function(){showDialog(markup,cbRegisterRender);});}
function cbLoginRender(){initLoginValidation();initForgotPasswordValidation();initLoginSubmit();initFBLogin();initGoogleLogin();initForgotPasswordSubmit();$('#forgotPassword').click(function(){$('#loginContent').hide();$('#forgotPasswordContent').show();});$('#backToLogin').click(function(){$('#loginContent').show();$('#forgotPasswordContent').hide();});}
function cbRegisterRender(){initRegisterValidation();initRegisterSubmit();initFBRegister();initGoogleRegister();}
function initGoogleRegister(){$('#googleRegisterBtn').click(function(e){window.open('/ty2/account/googlelogin/','GoogleLogin','width=900, height=500');return false;});}
function initFBRegister(){$('#fbRegisterBtn').click(function(e){window.open('/ty2/account/fblogin/','FacebookLogin','width=900, height=500');return false;});}
function initGoogleLogin(){$('#googleLoginBtn').click(function(e){window.open('/ty2/account/googlelogin/','GoogleLogin','width=900, height=500');return false;});}
function initFBLogin(){$('#fbLoginBtn').click(function(e){window.open('/ty2/account/fblogin/','FacebookLogin','width=900, height=500');return false;});}
function initLoginValidation(){var validationRules={email:{required:true,email:true},password:{required:true}};$('#loginForm').validate({rules:validationRules,onsubmit:false,errorPlacement:function(error,element){return true;},errorElement:"nothing",errorClass:"invalid",validClass:"success"});}
function initLoginSubmit(){$('#loginSubmit').click(function(e){e.stopPropagation();$form=$('#loginForm');if(!$form.valid())return;$('#loginSubmit').hide();$('#loginSubmitWait').show();$.ajax({url:'/api/account/login/',type:'POST',dataType:'json',data:{email:$form.find('input[name=email]').val(),password:$form.find('input[name=password]').val(),remember:$form.find('input[name=remember]').is(':checked')?1:0},success:function(response){if(response.success){$('.account-dialog').qtip('hide');$('#authInfoLinks .logged-in').show();$('#authInfoLinks .logged-out').hide();ty.utils.showStickyNotification(response.data.message);}else{$form.find('.msg').html(response.error.message);}},failure:function(){$form.find('.msg').html("Some problem occurred. Please try again.");},complete:function(){$('#loginSubmit').show();$('#loginSubmitWait').hide();}});return false;});}
function initRegisterValidation(){var validationRules={name:{required:true,rangelength:[3,50]},email:{required:true,email:true}};$('#registerForm').validate({rules:validationRules,onsubmit:false,errorPlacement:function(error,element){return true;},errorElement:"nothing",errorClass:"invalid",validClass:"success"});}
function initRegisterSubmit(){$('#registerSubmit').click(function(e){e.stopPropagation();$form=$('#registerForm');if(!$form.valid())return;$('#registerSubmit').hide();$('#registerSubmitWait').show();$.ajax({url:'/api/account/register/',type:'POST',dataType:'json',data:{name:$form.find('input[name=name]').val(),email:$form.find('input[name=email]').val()},success:function(response){if(response.success){$('#registerContent .form-content').hide();$('#registerContent .message').html(response.data.message).show();}else{$form.find('.msg').html(response.error.message);}},failure:function(){$form.find('.msg').html("Some problem occurred. Please try again.");},complete:function(){$('#registerSubmit').show();$('#registerSubmitWait').hide();}});return false;});}
function initForgotPasswordValidation(){var validationRules={email:{required:true,email:true}};$('#forgotPasswordForm').validate({rules:validationRules,onsubmit:false,errorPlacement:function(error,element){return true;},errorElement:"nothing",errorClass:"invalid",validClass:"success"});}
function initForgotPasswordSubmit(){$('#forgotPasswordSubmit').click(function(e){e.stopPropagation();$form=$('#forgotPasswordForm');if(!$form.valid())return;$('#forgotPasswordSubmit').hide();$('#forgotPasswordSubmitWait').show();$.ajax({url:$form.attr('action'),type:'POST',dataType:'json',data:{email:$form.find('input[name=email]').val()},success:function(response){if(response.success){$('#forgotPasswordContent .form-content').hide();$('#forgotPasswordContent .message').html(response.data.message).show();}else{$form.find('.msg').html(response.error.message);}},failure:function(){$form.find('.msg').html("Some problem occurred. Please try again.");},complete:function(){$('#forgotPasswordSubmit').show();$('#forgotPasswordSubmitWait').hide();}});return false;})}
function showDialog(markup,renderCallback){$('<div/>').qtip({prerender:true,content:{text:markup,title:{button:'Close'}},position:{my:'center',at:'center',target:$(window)},show:{ready:true,solo:'true',modal:{on:true,blur:false}},hide:false,style:'qtip-light qtip-dialog account-dialog',events:{render:function(){renderCallback();},hide:function(event,api){api.destroy();}}});}};ty.account.Auth();;$(function(){loadHdrCityDetls();$("body").on('click',function(){dropDownEvents();$('a.onwdrRght').removeClass('more-link-active');});});function hideDropUps(ddContnr,isFromToDDContnr,searchCityTB,toFromDDResult){if($(".contactNoContnr").hasClass("active")){$(".contactNoContnr").removeClass("active");}
$(".dropDown").hide();}
function dropDownEvents(){if($(".ui-autocomplete").is(':visible')){$("#fromCityDD").val('');$("#fromCityDD").autocomplete("search",[''])}
hideDropUps();if($(".dropDown").is(':visible')){$(".ddContnr").removeClass("active");$(".dropDown").hide();if($(".srchBusesDDWrap.active").size()>0){$(".srchBusesDDWrap.active").removeClass('active');}}}
function hdrContactDDSlideUp(contactNoDD,contactNoContnr){contactNoDD.hide();$(contactNoContnr).removeClass('active');}
function loadHdrCityDetls(){function hideHeaderContactDD(){if($(".contactNoDD").is(':visible')){var contactNoDD=$(".contactNoDD");var contactNoContnr=$(".contactNoContnr");hdrContactDDSlideUp(contactNoDD,contactNoContnr);}}
$(".contactDetlsBlk").on('click',function(e){e.preventDefault();e.stopPropagation();$(".ddContnr,.srchBusesDDWrap").removeClass("active");$('.contactNoDD > ul > li').eq(0).focus();var contactNoDD=$(".contactNoDD");var contactNoContnr=$(".contactNoContnr");$(".dropDown").not(contactNoDD).hide();if(contactNoDD.is(':visible')){hdrContactDDSlideUp(contactNoDD,contactNoContnr);}else{$(".contactNoContnr").addClass('active');contactNoDD.show();}});function setDefaultCity(index){var seltdLoctn=$(".contactNoDD li:eq("+index+")").children("label").text();var seltdLoctnNo=$(".contactNoDD li:eq("+index+")").children("span").text();$(".currLoctn").text(seltdLoctn);$(".currNo").text(seltdLoctnNo);}
$(".contactNoDD li").on('mouseenter',function(e){$this=$(this);$this.siblings().removeClass('cityLi-hover');$this.addClass('cityLi-hover');});$(".contactNoDD li").on('click',function(e){var clkdItem=$(this);var seltdLoctn=clkdItem.children("label").text();var seltdLoctnNo=clkdItem.children("span").text();$(".contactNoBlk  .currLoctn").text(seltdLoctn);$(".contactNoBlk  .currNo").text(seltdLoctnNo);$(".contactNoDD").slideUp();$('.contactNoDD, .contactNoContnr').removeClass('active');$(".contactNoDD li").show();clkdItem.hide();});};ty=window.ty||{};ty.stickyNoteTimeout=0;ty.utils={formatTime:function(t,hours24){var z=new Date();var off=z.getTimezoneOffset();t=(330+off)*60*1000+t;var d=new Date(t),hours=d.getHours(),minutes=d.getMinutes(),ampm,ret;if(hours24){hours=hours<10?'0'+hours:hours;minutes=minutes<10?'0'+minutes:minutes;ret=hours+':'+minutes;}else{ampm=hours>=12?'PM':'AM';hours=hours%12;hours=hours?hours:12;minutes=minutes<10?'0'+minutes:minutes;ret=hours+':'+minutes+' '+ampm;}
return ret;},formatDate:function(t,reverse){var z=new Date();var off=z.getTimezoneOffset();t=(330+off)*60*1000+t;var d=new Date(t),day=d.getDate(),month=d.getMonth()+1,year=d.getFullYear(),ret;if(day<10)day="0"+day;if(month<10)month="0"+month;if(reverse){ret=year+"-"+month+"-"+day;}else{ret=day+"-"+month+"-"+year;}
return ret;},formatDate2:function(t,reverse){var z=new Date();var off=z.getTimezoneOffset();t=(330+off)*60*1000+t;var d=new Date(t),day=d.getDate(),month=d.getMonth(),year=d.getFullYear(),ret;var months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];if(day<10)day="0"+day;if(reverse){ret=year+"-"+months[month]+"-"+day;}else{ret=day+"-"+months[month]+"-"+year;}
return ret;},getDuration:function(departureTime,arrivalTime){var oDep=new Date(departureTime),oArr=new Date(arrivalTime);return oArr.getTime()-oDep.getTime();},formatDuration:function(duration){var totalMins=duration/(1000*60),ret="";hours=Math.floor(totalMins/60);minutes=totalMins-(hours*60);if(hours>0){ret=hours+"h";}
if(minutes>0){ret+=" "+minutes+"m";}
return ret;},getDay:function(t){var d=new Date(t);return d.getDay();},getTimeIconClass:function(ts){var z=new Date();var off=z.getTimezoneOffset();ts=(330+off)*60*1000+ts;var d=new Date(ts),hour=d.getHours();if(hour>=5&&hour<9)return"morning";if(hour>=9&&hour<17)return"noon";if(hour>=17&&hour<21)return"evening";if(hour>=21||hour<5)return"night";},getRandomId:function(prefix){return prefix+parseInt(Math.random()*1000000,10);},getLeftBound:function($el){return $el.offset().left;},getRightBound:function($el){return($(window).width()-($el.offset().left+$el.outerWidth()));},logError:function(module,data){$.ajax({url:'/'+module+'/LogJSError',dataType:"html",data:{out:'html',ajx:1,info:data},success:function(response){}});},showAlert:function($container,msg,type){var $el=$container.find('.ty-alert');$el.find('.text').html(msg);if(type=="success"){$el.addClass('success');}else if(type=="warning"){$el.addClass('warning');}else if(type=="error"){$el.addClass('error');}else{$el.addClass('notice');}
$el.show();},hideAlert:function($container){var $el=$container.find('.ty-alert');$el.hide();},globalAlert:function(msg){var markup='<div class="ty-global-alert"><span class="alert-icon"></span><a class="msg">'+msg+'</a><span class="close-icon"></span></div>';$('body').prepend(markup);$('.ty-global-alert .close-icon').click(function(){$('.ty-global-alert').hide();});},isInteger:function(n){return(Math.floor(n)==n&&$.isNumeric(n));},capitalize:function(s){return s.charAt(0).toUpperCase()+s.slice(1).toLowerCase();},getFormattedDateForURL:function(dateString){dateString=dateString.replace(/-/g,' ');var d=new Date(dateString),day=d.getDate(),month=d.getMonth()+1,year=d.getFullYear();if(day<10)day="0"+day;if(month<10)month="0"+month;return day+"-"+month+"-"+year;},showStickyNotification:function(msg){window.clearTimeout(ty.stickyNoteTimeout);$('#stickyNote .msg').html(msg);$('#stickyNote').show();ty.stickyNoteTimeout=window.setTimeout(function(){$('#stickyNote').hide();},5000);}};ty=window.ty||{};ty.SearchWidget=function(){var fromCityNames=[],toCityNames=[],stateNames=[],isCityListFetched=false;$(function(){initHandleBackButton();init();});function initHandleBackButton(){$(window).bind("pageshow",function(){$('#searchProgress').hide();$('#homeContent').show();});}
function init(){$('#fromCity').select();initCities();initCityAutocomplete();initDatePicker();initSearchSubmit();validateNumericFields();initSwapCities();}
function validateNumericFields(){$(".numeric").numeric(false);}
function initSwapCities(){$('#swapCities').click(function(){var fromCity=$('#fromCity').val(),toCity=$('#toCity').val();$('#fromCity').val(toCity);$('#toCity').val(fromCity);});}
function initCities(){$.ajax({url:ty.home.data.citiesUrl,dataType:'json',success:function(result){var cities=result.data.cities;for(var i=0;i<cities.length;i++){var name=cities[i].CityName,isFrom=cities[i].IsFrom,isTo=cities[i].IsTo,state=cities[i].StateName;if(isFrom){fromCityNames.push(name);}
if(isTo){toCityNames.push(name);}
stateNames[name]=state.toLowerCase();}
isCityListFetched=true;},complete:function(){loadSpriteImg();}});}
function loadSpriteImg(){$(".agent_ico, .ladiesseat, .liveinventory_ico, .pigybank_ico, .tycard_ico").addClass("spritebg2");}
function getFilteredCities(request,cities){var str=request.term.toLowerCase();var ret=$.map(cities,function(item){if(item.indexOf(str)===0){return ucwords(item);}else{return null;}});return ret;}
function getCityMatch(str,cities){str=str.toLowerCase();for(var i=0;i<cities.length;i++){if(cities[i].indexOf(str)===0){return ucwords(cities[i]);}}
return str;}
function autoSelectCity(el,ui,cities){if(ui.item===null){var $el=$(el),inputText=$el.val(),validText;if(inputText.length>0){validText=getCityMatch(inputText,cities);$el.val(validText);}}}
function initCityAutocomplete(){$('#fromCity').autocomplete({source:function(request,response){response(getFilteredCities(request,fromCityNames));},change:function(event,ui){autoSelectCity(this,ui,fromCityNames);},select:function(event,ui){$(this).removeClass('invalid');$('#toCity').focus();$('#toCity').select();if(event.keyCode==9){event.preventDefault();}
getLocalizedCC();},delay:0,autoFocus:true});$('#toCity').autocomplete({source:function(request,response){response(getFilteredCities(request,toCityNames));},change:function(event,ui){autoSelectCity(this,ui,toCityNames);},select:function(event,ui){$(this).removeClass('invalid');$('#departDate').focus();if(event.keyCode==9){event.preventDefault();}},delay:0,autoFocus:true});}
function initDatePicker(){$('.datepicker').datepicker({numberOfMonths:2,dayNamesMin:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],firstDay:1,minDate:ty.home.data.minDate,maxDate:ty.home.data.maxDate,dateFormat:"D, d-M-yy"});$('#departDate').datepicker('option','defaultDate',ty.home.data.defaultDate);$('#departDate').datepicker('option','onSelect',function(dateText){$('#returnDate').datepicker('option','minDate',dateText);});$('#returnDate').datepicker('option','onSelect',function(dateText){$('#clearReturnDate').show();});$('#clearReturnDate').click(function(){$('#returnDate').val('');$(this).hide();});$('#departDateBtn').click(function(){$('#departDate').focus();});$('#returnDateBtn').click(function(){$('#returnDate').focus();});}
function ucwords(str){return(str+'').replace(/^([a-z\u00E0-\u00FC])|\s+([a-z\u00E0-\u00FC])/g,function($1){return $1.toUpperCase();});}
function getFormattedDateForURL(dateString){dateString=dateString.replace(/-/g,' ');var d=new Date(dateString),day=d.getDate(),month=d.getMonth()+1,year=d.getFullYear();if(day<10)day="0"+day;if(month<10)month="0"+month;return day+"-"+month+"-"+year;}
function isValidCity(city,cities){city=city.toLowerCase();for(var i=0;i<cities.length;i++){if(city===cities[i])return 1;}
return 0;}
function validateCity($el,cities){var city=$el.val();if(city===''||!isValidCity(city,cities)){$el.addClass("invalid");return false;}else{$el.removeClass("invalid");return true;}}
function formatSearchProgressJourneyDate(departDate){var journeyDate=new Date(departDate);var day=journeyDate.getDate();if(day<=9){var tmp=departDate.split(' ');return tmp[0]+' 0'+tmp[1];}else{return departDate;}}
function showSearchProgress(fromCity,toCity,departDate){$('#homeContent').hide();$('#searchProgress').show();$('#prgFromCity').html(ucwords(fromCity));$('#prgToCity').html(ucwords(toCity));$('#prgJourneyDate').html(formatSearchProgressJourneyDate(departDate));}
function initSearchSubmit(){$('#submitSearch').click(function(){var valid1=true,valid2=true;if(isCityListFetched){valid1=validateCity($('#fromCity'),fromCityNames);valid2=validateCity($('#toCity'),toCityNames);}
if(valid1&&valid2){var fromCity=$('#fromCity').val().toLowerCase(),toCity=$('#toCity').val().toLowerCase(),departDate=$('#departDate').val(),returnDate=$('#returnDate').val(),hop="direct",mode;if(returnDate===''){mode="oneway";}else{mode="roundtrip";}
var $form=$('#searchForm');$form.find("input[name=mode]").val(mode);$form.find("input[name=hop]").val(hop);$form.find("input[name=fromCity]").val(fromCity);$form.find("input[name=toCity]").val(toCity);$form.find("input[name=departDate]").val(getFormattedDateForURL(departDate));if(returnDate!==''){$form.find("input[name=returnDate]").val(getFormattedDateForURL(returnDate));}else{$form.find("input[name=returnDate]").remove();}
$form.submit();showSearchProgress(fromCity,toCity,departDate);}});}
function getLocalizedCC(){var cityName=$("#fromCity").val().toLowerCase(),stateName=stateNames[cityName]||"karnataka";$("#fcs").val(stateName.toLowerCase());if(cityName.search(/mumbai/i)>-1){var cc="10";}
else if(cityName.search(/vashi/i)>-1){var cc="10";}
else if(cityName.search(/thane/i)>-1){var cc="10";}
else if(cityName.search(/delhi/i)>-1){var cc="12";}
else if(cityName.search(/new delhi/i)>-1){var cc="12";}
else if(cityName.search(/kolkata/i)>-1){var cc="9";}
else if(cityName.search(/chandigarh/i)>-1){var cc="3";}
else if(cityName.search(/ludhiana/i)>-1){var cc="3";}
else if(cityName.search(/amritsar/i)>-1){var cc="3";}
else if(cityName.search(/jalandhar/i)>-1){var cc="3";}
else if(cityName.search(/indore/i)>-1){var cc="7";}
else if(cityName.search(/jaipur/i)>-1){var cc="8";}
else if(cityName.search(/nagpur/i)>-1){var cc="11";}
else if(cityName.search(/surat/i)>-1){var cc="16";}
else if(cityName.search(/baroda/i)>-1){var cc="2";}
else if(cityName.search(/goa/i)>-1){var cc="5";}
else if(cityName.search(/pune/i)>-1){var cc="13";}
else if(cityName.search(/raipur/i)>-1){var cc="14";}
else if(cityName.search(/rajkot/i)>-1){var cc="15";}
else if(cityName.search(/chennai/i)>-1){var cc="4";}
else{switch(stateName){case"karnataka":case"kerala":case"":var cc="0";break;case"andhra pradesh":var cc="6";break;case"tamil nadu":var cc="4";break;case"punjab":var cc="3";break;case"west bengal":var cc="9";break;default:var cc="1";break;}}
selectCC(cc);}
function selectCC(index){var seltdLoctn=$(".contactNoDD li:eq("+index+")").children("label").text();var seltdLoctnNo=$(".contactNoDD li:eq("+index+")").children("span").text();$(".currLoctn").text(seltdLoctn);$(".currNo").text(seltdLoctnNo);}};ty=window.ty||{};ty.SearchTable=function(routes,pickups,$searchResultsEl){var $searchResultsTable,oData=[],oTable,pickupAreas={},maxSeatsLimit={},onwardJourney=null,onwardSeats=null,STICKY_HEIGHT=69,fromCity=encodeURI(ty.search.data.fromCity),toCity=encodeURI(ty.search.data.toCity);if(ty.search.data.hasOwnProperty('onwardJourney')){onwardJourney=$.parseJSON(ty.search.data.onwardJourney);}
if(ty.search.data.hasOwnProperty('onwardSeats')){onwardSeats=$.parseJSON(ty.search.data.onwardSeats);}
var fareTypeLabel={'SeaterFareNAC':'Seater Non AC','SeaterFareAC':'Seater AC','SleeperFareNAC':'Sleeper Non AC','SleeperFareAC':'Sleeper AC'};var amenitiesMap={'wb':{cls:'bottle',label:'Water Bottle'},'tv':{cls:'tv',label:'TV'},'wf':{cls:'wifi',label:'WiFi'},'cp':{cls:'charging',label:'Charging Point'},'tl':{cls:'toilet',label:'Toilet'},'sk':{cls:'snacks',label:'Snacks'},'pt':{cls:'tv',label:'Personal TV'},'bk':{cls:'blanket',label:'Blanket'}};init();function init(){initOnwardJourneyInfo();initData();initResultsTable();initScrollHandler();}
function initOnwardJourneyInfo(){if(!onwardJourney)return;$el=$('#onwardTab');$tabsEl=$('#searchInfo .journey-tabs');$el.mouseenter(function(){$tabsEl.addClass('info');}).mouseleave(function(){$tabsEl.removeClass('info');});$el.qtip({prerender:true,content:{text:$('#onwardJourneyInfo').html(),title:{button:false}},position:{my:'top-left',at:'bottom-left',target:$('#onwardTab')},show:{event:'click',solo:'true'},hide:{event:'unfocus, click',},style:{classes:'qtip-filter qtip-info',tip:false},events:{show:function(event,api){$el.addClass('info-active');},hide:function(event,api){$el.removeClass('info-active');},render:function(event,api){var $qtip=$(event.target);var duration=ty.utils.getDuration(onwardJourney.depTimeTS*1000,onwardJourney.arrTimeTS*1000);var depTime=onwardJourney.depTimeTS*1000;var arrTime=onwardJourney.arrTimeTS*1000;$qtip.find('td.duration .time').html(ty.utils.formatDuration(duration));$qtip.find('td.departure .icon .timeslot-icon').addClass(ty.utils.getTimeIconClass(depTime));$qtip.find('td.departure .time').html(ty.utils.formatTime(depTime));$qtip.find('td.arrival .icon .timeslot-icon').addClass(ty.utils.getTimeIconClass(arrTime));$qtip.find('td.arrival .time').html(ty.utils.formatTime(arrTime));var depDay=ty.utils.getDay(depTime);var arrDay=ty.utils.getDay(arrTime);if(arrDay-depDay==1){$qtip.find('td.duration .msg').html('Arrive next day');}}}});}
function initData(){for(var i=0;i<routes.length;i++){var oFares={'SeaterFareNAC':[routes[i].SeaterFareNAC],'SeaterFareAC':[routes[i].SeaterFareAC],'SleeperFareNAC':[routes[i].SleeperFareNAC],'SleeperFareAC':[routes[i].SleeperFareAC]};var tmpArr=[routes[i].CompanyName,routes[i].BusTypeName,routes[i].depTimeTS*1000,ty.utils.getDuration(routes[i].depTimeTS*1000,routes[i].arrTimeTS*1000),routes[i].arrTimeTS*1000,routes[i].IsMTicketAllowed,routes[i].AvailableSeats,routes[i].Fare,routes[i].RouteScheduleId,routes[i].CompanyId,oFares];var oDiscount={'isValid':routes[i].HasDiscountPolicy,'amount':routes[i].DiscountAmt,'percent':routes[i].DiscountPer};tmpArr.push(oDiscount);var oPics={'hasPics':routes[i].HasBusPics,'key':routes[i].BusPicsKey};tmpArr.push(oPics);tmpArr.push(routes[i].Amenities);oData.push(tmpArr);}
for(var i=0;i<pickups.length;i++){var rsIdArr=pickups[i].RSIDs;for(var j=0;j<rsIdArr.length;j++){var rsId=rsIdArr[j];if(!pickupAreas[rsId])pickupAreas[rsId]=[];pickupAreas[rsId].push(pickups[i].AreaID);}}}
function getOperators(){var ret=[],op={},seatsLimit=$.parseJSON(ty.search.constants.MAX_SEATS_LIMIT);for(var i=0;i<routes.length;i++){if(!op.hasOwnProperty(routes[i].CompanyName)){ret.push(routes[i].CompanyName);op[routes[i].CompanyName]=1;maxSeatsLimit[routes[i].CompanyId]=seatsLimit[routes[i].CompanyId]||seatsLimit['_default'];}}
ret.sort();return ret;}
function getFareRange(){var minFare=999999,maxFare=0;for(var i=0;i<routes.length;i++){minFare=Math.min(minFare,routes[i].Fare);maxFare=Math.max(maxFare,routes[i].Fare);}
return{min:minFare,max:maxFare};}
function formatOperatorName(s,n){if(s.length>n){s=s.substr(0,n);return s+"...";}
return s;}
function formatPickupName(s){var tmp=s.split(' '),ret="";for(var i=0;i<tmp.length;i++){if(ret.length)ret+=" ";ret+=ty.utils.capitalize(tmp[i]);}
return ret;}
function isMultipleFare(oFares){var c=0;for(type in oFares){if(oFares.hasOwnProperty(type)){var fareArr=oFares[type];for(var i=0;i<fareArr.length;i++){if(fareArr[i]>0)c++;}}}
return c>=2;}
function getMultipleFareMarkup(oFares,oDiscount){var markup='';for(type in oFares){if(oFares.hasOwnProperty(type)){var fareArr=oFares[type];fareArr.sort();var fareStr='';for(var i=0;i<fareArr.length;i++){var fare=parseFloat(fareArr[i]).toFixed(0);var discount=0;if(oDiscount&&oDiscount.isValid){if(oDiscount.amount){discount=oDiscount.amount;}else{discount=Math.floor(oDiscount.percent*fare/100);}}
if(fare>0){if(discount){var newfare=fare-discount;fareStr+='<span class=strike>'+fare+'</span>';fareStr+='<span>'+newfare+'</span>';}else{fareStr+='<span>'+fare+'</span>';}}
if(fareStr.length&&i!=fareArr.length-1)fareStr+='/';}
if(fareStr.length){markup+=fareTypeLabel[type]+': Rs '+fareStr+'<br/>';}}}
return markup;}
function initResultsTable(){var filterContentMarkup=$('#filterContentTmpl').html();function getOperatorTitleMarkup(){var markup='',operators=getOperators();markup+='<div id="sortOperator" class="title"><strong>Bus Operator<span></span></strong></div>';markup+='<button class="show-filter-btn" id="operatorFilterBtn" data-filter="operator"><strong>ALL OPERATORS</strong><span class="arrow"></span></button>';markup+=filterContentMarkup;markup+='<div class="filter-options-container" id="operatorFilter">';markup+='<div class="filter-options operator">';markup+='<div>';markup+='<input id="allOperators" type="checkbox" name="allOperators" value="All Operators" checked="checked">';markup+='<label for="allOperators">All Operators</label>';markup+='</div>';markup+='<div class="operator-separator clearfix">';markup+='<div class="divider left" style="width:40px;"></div>';markup+='<div class="text left">Or select specific operators</div>';markup+='<div class="divider left" style="width:660px;"></div>';markup+='</div>';markup+='<div class="clearfix">';for(i=0;i<operators.length;i++){var id=ty.utils.getRandomId('operator');markup+='<div class="col">';markup+='<input id="'+id+'" type="checkbox" name="'+operators[i]+'" value="'+operators[i]+'">';markup+='<label for="'+id+'">'+formatOperatorName(operators[i],40)+'</label>';markup+='</div>';}
markup+='</div>';markup+='</div>';markup+='</div>';return markup;}
function getBusTypeTitleMarkup(){var markup='';markup+='<div id="sortBusType" class="title"><strong>Bus Type<span></span></strong></div>';markup+='<button class="show-filter-btn" id="busTypeFilterBtn" data-filter="busType"><strong>ALL TYPES</strong><span class="arrow"></span></button>';markup+=filterContentMarkup;markup+=$('#busTypeFilterTmpl').html();return markup;}
function getDepartureTitleMarkup(){var markup='';markup+='<div id="sortDeparture" class="title"><strong>Departure<span></span></strong></div>';markup+='<button class="show-filter-btn" id="departureFilterBtn" data-filter="departure"><strong>TIME</strong><span class="arrow"></span></button>';markup+=filterContentMarkup;markup+='<button class="show-filter-btn" id="pickupFilterBtn" data-filter="pickup"><strong>PICKUP</strong><span class="arrow"></span></button>';markup+=filterContentMarkup;markup+='<div class="filter-options-container" id="pickupFilter">';markup+='<div class="filter-options pickup">';markup+='<div>';markup+='<input id="allPickups" type="checkbox" name="allPickups" value="All Pickups" checked="checked">';markup+='<label for="allPickups">All Pickups</label>';markup+='</div>';markup+='<div class="pickup-separator clearfix">';markup+='<div class="divider left" style="width:40px;"></div>';markup+='<div class="text left">Or select specific pickups</div>';markup+='<div class="divider left" style="width:660px;"></div>';markup+='</div>';markup+='<div class="clearfix">';for(i=0;i<pickups.length;i++){var id=ty.utils.getRandomId('pickup');markup+='<div class="col">';markup+='<input id="'+id+'" type="checkbox" value="'+pickups[i].AreaID+'">';markup+='<label for="'+id+'">'+formatPickupName(pickups[i].AreaName)+'</label>';markup+='</div>';}
markup+='</div>';markup+='</div>';markup+='</div>';markup+=$('#departureFilterTmpl').html();return markup;}
function getDurationTitleMarkup(){var markup='';markup+='<div id="sortDuration" class="title"><strong>Duration<span></span></strong></div>';return markup;}
function getArrivalTitleMarkup(){var markup='';markup+='<div id="sortArrival" class="title"><strong>Arrival<span></span></strong></div>';return markup;}
function getmTicketTitleMarkup(){var markup='';markup+='<div id="sortmTicket" class="title"><strong>mTicket<span></span></strong></div>';return markup;}
function getSeatsTitleMarkup(){var markup='';markup+='<div id="sortSeats" class="title"><strong>Seats<span></span></strong></div>';return markup;}
function getFareTitleMarkup(){var markup='';markup+='<div id="sortFare" class="title"><strong>Fare<span></span></strong></div>';markup+='<button class="show-filter-btn" id="fareFilterBtn" data-filter="fare"><strong>ALL FARES</strong><span class="arrow"></span></button>';markup+=filterContentMarkup;markup+=$('#fareFilterTmpl').html();return markup;}
$searchResultsEl.html('<table id="searchResultsTable"></table>');$searchResultsTable=$('#searchResultsTable');oTable=$searchResultsTable.dataTable({"aoColumns":[{"sTitle":getOperatorTitleMarkup(),"sClass":"operator"},{"sTitle":getBusTypeTitleMarkup(),"sClass":"bus-type"},{"sTitle":getDepartureTitleMarkup(),"sClass":"departure"},{"sTitle":getDurationTitleMarkup(),"sClass":"duration"},{"sTitle":getArrivalTitleMarkup(),"sClass":"arrival"},{"sTitle":getmTicketTitleMarkup(),"sClass":"m-ticket"},{"sTitle":getSeatsTitleMarkup(),"sClass":"seats"},{"sTitle":getFareTitleMarkup(),"sClass":"fare"}],"aaData":oData,"bPaginate":false,"aaSorting":[[2,'asc']],"aoColumnDefs":[{"aTargets":[0],"mRender":function(data,type,full){if(type=='display'){var markup='',routeId=full[8],oDiscount=full[11],discount=0,oPics=full[12],journeyDate=ty.utils.formatDate(full[2],true);if(full[6]>0){if(oDiscount.isValid){if(oDiscount.amount){discount=oDiscount.amount;markup+='<div class="offer">DEAL: Rs. '+discount+' Off <span class="corner"></span><strong>&bull;</strong></div>';}else{discount=Math.floor(oDiscount.percent*data/100);markup+='<div class="offer">DEAL: '+oDiscount.percent+'% Off <span class="corner"></span><strong>&bull;</strong></div>';}}}
if(data.length>23){markup+='<h3 title="'+data+'">'+formatOperatorName(data,20)+'</h3>';}else{markup+='<h3>'+data+'</h3>';}
markup+='<div class="links">';markup+='<span class="cancellation-policy"><a class="route-info-overlay" href="javascript:void(0)" rel="/ty2/resource/getRouteInfo/'+routeId+'/'+journeyDate+'/?from='+fromCity+'&to='+toCity+'&out=html&ajx=1&tab=3">Canc. Policy</a></span>';if(oPics.hasPics){markup+='<span class="show-photos" data-key="'+oPics.key+'" data-operator="'+data+'"><a href="javascript:void(0)"><span class="icon"></span>Photos</a></span>';}
markup+='</div>';return markup;}
return data;}},{"aTargets":[1],"mRender":function(data,type,full){if(type=='display'){var markup='',routeId=full[8],amenities=full[13];markup+='<div class="bus-type-name">'+full[1]+'</div>';if(amenities&&amenities.length){markup+='<div class="amenities">';for(var i=0;i<amenities.length;i++){var cls=amenitiesMap[amenities[i]]['cls'],label=amenitiesMap[amenities[i]]['label'];markup+='<span class="icon '+cls+'" data-title="'+label+'"></span>';}
markup+='</div>';}
return markup;}else{return data;}}},{"aTargets":[2],"mRender":function(data,type,full){if(type=='display'){var markup='',routeId=full[8],journeyDate=ty.utils.formatDate(full[2],true);markup+='<div class="icon"><span class="timeslot-icon '+ty.utils.getTimeIconClass(data)+'"></span></div>';markup+='<div class="time">'+ty.utils.formatTime(data)+'</div>';markup+='<div><a class="route-info-overlay" href="javascript:void(0)" rel="/ty2/resource/getRouteInfo/'+routeId+'/'+journeyDate+'/?from='+fromCity+'&to='+toCity+'&out=html&ajx=1&tab=1">Pickups</a></div>';return markup;}else{return data;}}},{"aTargets":[3],"sType":'custom-date',"mRender":function(data,type,full){if(type=='display'){var markup='',arrDay=ty.utils.getDay(full[4]),depDay=ty.utils.getDay(full[2]);markup+='<div class="icon"><span class="duration-arrow"></span></div>';markup+='<div class="time">'+ty.utils.formatDuration(data)+'</div>';if(arrDay-depDay==1){markup+='<div>Arrive next day</div>';}
return markup;}else{if(data==full[2]){return 0;}else{return data;}}}},{"aTargets":[4],"sType":'custom-date',"mRender":function(data,type,full){if(type=='display'){var markup='',routeId=full[8],journeyDate=ty.utils.formatDate(full[2],true);if(data==full[2]){markup+='<div class="time">NA</div>';}else{markup+='<div class="icon"><span class="timeslot-icon '+ty.utils.getTimeIconClass(data)+'"></span></div>';markup+='<div class="time">'+ty.utils.formatTime(data)+'</div>';}
markup+='<div><a class="route-info-overlay" href="javascript:void(0)" rel="/ty2/resource/getRouteInfo/'+routeId+'/'+journeyDate+'/?from='+fromCity+'&to='+toCity+'&out=html&ajx=1&tab=2">Dropoffs</a></div>';return markup;}else{if(data==full[2]){return 0;}else{return data;}}}},{"aTargets":[5],"mRender":function(data,type,full){if(type=='display'){var markup='';if(data){markup+='<div class="icon"><span class="yes" title="mTicket SMS can be used to board this bus"></span></div>';}else{markup+='<div class="icon"><span class="no" title="mTicket is NOT allowed for boarding this bus. Kindly take a print out of the ticket."></span></div>';}
return markup;}
return data;}},{"aTargets":[6],"sType":'numeric',"mRender":function(data,type,full){if(type=='display'){if(data){if(data>0){if(full[9]==3930)return 20;return data;}else if(data==0){return"none";}else{return"Avlbl";}}else{return"NA";}}
return data;}},{"aTargets":[7],"mRender":function(data,type,full){var oDiscount=full[11],discount=0;if(oDiscount.isValid){if(oDiscount.amount){discount=oDiscount.amount;}else{discount=Math.floor(oDiscount.percent*data/100);}}
if(type=='display'){var markup='',routeId=full[8],journeyDate=ty.utils.formatDate(full[2],true),companyId=full[9],primaryFare=data,oFares=full[10];if(full[6]==0){markup+='<div class="amount"><strong class="strike">'+formatFare(primaryFare)+'</strong></div>';markup+='<div class="select"><button class="primary-btn select-seats" data-rsid="'+routeId+'" disabled="disabled">Sold Out</button></div>';}else{markup+='<div class="amount" data-fare="'+data+'">';if(oDiscount.isValid){markup+='<strong class="orig-fare strike">'+formatFare(primaryFare)+'</strong>';}
markup+='<strong>'+formatFare(primaryFare-discount)+'</strong>';if(isMultipleFare(oFares)){var m=getMultipleFareMarkup(oFares,oDiscount);markup+='<span class="multi" data-fareinfo="'+m+'"></span>';}
markup+='</div>';markup+='<div class="select">';markup+='<button class="primary-btn select-seats" data-rsid="'+routeId+'" data-journeydate="'+journeyDate+'" data-companyid="'+companyId+'">Select Seats</button>';markup+='<div class="loadingBar right" style="display:none"><span>Just a moment</span></div>';markup+='</div>';}
return markup;}else{return data-discount;}}}],"oLanguage":{"sZeroRecords":"No buses found"},"fnInitComplete":function(oSettings,json){addTheadGradient();$('#filterTmpls').remove();initOperatorNameTooltip();initAmenitiesTooltip();initMultipleFareTooltip();initMTicketTooltip();initFilters();initRouteInfoOverlay();initSeatsDisplay();initPhotos();},"fnDrawCallback":function(){var $tbody=$(this).find('tbody');$tbody.find('tr.active').removeClass('active');$tbody.find('tr').each(function(index){var $row=$(this);var seats=$row.find('td.seats').html();if(seats=='NA'){$tbody.append('<tr>'+$row.html()+'</tr>');$row.remove();}});$('.qtip-red').hide();}});initResultsTableSort(oTable);}
function initResultsTableSort(oTable){oTable.find('thead th').unbind();initCustomSortFunctions();oTable.fnSortListener(document.getElementById('sortOperator'),0);oTable.fnSortListener(document.getElementById('sortDeparture'),2);oTable.fnSortListener(document.getElementById('sortDuration'),3);oTable.fnSortListener(document.getElementById('sortArrival'),4);oTable.fnSortListener(document.getElementById('sortmTicket'),5);oTable.fnSortListener(document.getElementById('sortSeats'),6);oTable.fnSortListener(document.getElementById('sortFare'),7);}
function initCustomSortFunctions(){jQuery.fn.dataTableExt.oSort['custom-date-asc']=function(a,b){if(a==0)return 1;if(b==0)return-1;var x=new Date(a);var y=new Date(b);return((x<y)?-1:((x>y)?1:0));};jQuery.fn.dataTableExt.oSort['custom-date-desc']=function(a,b){if(a==0)return 1;if(b==0)return-1;var x=new Date(a);var y=new Date(b);return((x<y)?1:((x>y)?-1:0));};}
function initOperatorNameTooltip(){$searchResultsTable.find('td.operator h3[title]').qtip({style:{classes:'qtip-blue'},position:{my:'bottom center',at:'top center'}});}
function initAmenitiesTooltip(){$searchResultsTable.find('td.bus-type .amenities .icon').qtip({content:{text:function(){return $(this).data('title')}},style:{classes:'qtip-blue qtip-amenities'},position:{my:'bottom center',at:'top center'}});}
function initMultipleFareTooltip(){$searchResultsTable.find('td.fare .multi').qtip({content:{text:function(){return $(this).data('fareinfo')}},style:{classes:'qtip-blue qtip-multifare'},position:{my:'bottom right',at:'top center'}});}
function initMTicketTooltip(){$searchResultsTable.find('td.m-ticket span[title]').qtip({style:{classes:'qtip-blue qtip-mticket'},position:{my:'bottom center',at:'top center'}});}
function addTheadGradient(){var getThHgt=$searchResultsTable.find('thead').height();$('.strip-table-hdbg').css('height',(getThHgt-1)+'px');}
function initUniform(){$('.filter-options input[type=checkbox], .filter-options input[type=radio]').uniform();}
function repositionFilters(){var st=$(window).scrollTop();if(st>=STICKY_HEIGHT){$('.filter-content.departure').css('left',0);$('.filter-content.pickup').css('left',0);$('.filter-content.fare').css('right',0);}else{if($searchResultsTable.length){var left=ty.utils.getLeftBound($searchResultsTable);var right=ty.utils.getRightBound($searchResultsTable);$('.filter-content.departure').css('left',left);$('.filter-content.pickup').css('left',left);$('.filter-content.fare').css('right',right);}}}
function initFilters(){var lastElementClicked;$(document).mousedown(function(e){lastElementClicked=$(e.target);});$('.show-filter-btn').click(function(event){var $this=$(this);var $el=$this.next('.filter-content');var $elContent=$el.find('.qtip-content');var filter=$this.data('filter');$el.addClass(filter);if($el.css('display')=='none'){if($elContent.html()==''){var content=$('#'+filter+'Filter').html();$elContent.html(content);initUniform();if($this.attr('id')=='operatorFilterBtn'){initOperatorFilter();}
if($this.attr('id')=='busTypeFilterBtn'){initBusTypeFilter();}
if($this.attr('id')=='departureFilterBtn'){initDepartureFilter();}
if($this.attr('id')=='pickupFilterBtn'){initPickupFilter();}
if($this.attr('id')=='fareFilterBtn'){initFareSlider();initFareFilter();}
$el.delegate('input','click',function(){$el.focus();});$el.blur(function(event){if(lastElementClicked.parents('.filter-content').length)return;var $link=$el.prev('.show-filter-btn');if(lastElementClicked.attr('id')!=$link.attr('id')&&lastElementClicked.parent().attr('id')!=$link.attr('id')){hideFilter($el,$link);}});}
showFilter($el,$this);repositionFilters();}else{hideFilter($el,$this);}});$('.filter-content').delegate('.qtip-close','click',function(){var $el=$(this).parent('.filter-content');var $link=$el.prev('.show-filter-btn');hideFilter($el,$link);});}
function hideFilter($el,$link){$el.hide();$link.removeClass('active');}
function showFilter($el,$link){$el.show();$el.focus();$link.addClass('active');}
function initRouteInfoOverlay(){$('tbody').on('click','a.route-info-overlay',function(event){var url=$(this).attr('rel');showDialog(url);return false;});}
function preloadImages(urls){$(urls).each(function(){$('<img/>')[0].src=this;});}
function initPhotos(){$('td.operator .show-photos').click(function(){var key=$(this).data('key'),operator=$(this).data('operator');$.get('/api/resource/buspictures/?key='+key,function(response){if(response.success&&response.data.images.length){showGallery(response.data.images,operator);}});});}
function showGallery(urls,operator){var n=urls.length,idx=0,$dialog;$('<div />').qtip({content:{text:getMarkup(),title:{button:'Close'}},position:{my:'center',at:'center',target:$(window)},show:{ready:true,modal:{on:true}},hide:false,style:'qtip-light qtip-dialog qtip-gallery',events:{render:function(){$('#busGalleryImage').html('<img src="'+urls[idx]+'">');preloadImages(urls.slice(1));$dialog=$(this);if(urls.length>1){$dialog.find('.nav.next').css('visibility','visible');}
$dialog.find('.nav').click(function(){var change=0;if($(this).hasClass('prev')){if(idx>0){idx--;change=1;}}else{if(idx<n-1){idx++;change=1;}}
if(change){updateMarkup();}});},hide:function(event,api){api.destroy();}}});function getMarkup(){var markup='';markup+='<div class="operator-name">';markup+='<strong>'+operator+'</strong>';markup+='</div>';markup+='<div class="clearfix">';markup+='<div class="left"><a class="nav prev" href="javascript:void(0);" style="visibility:hidden"></a></div>';markup+='<div class="img left" id="busGalleryImage"></div>';markup+='<div class="left"><a class="nav next" href="javascript:void(0);" style="visibility:hidden"></a></div>';markup+='</div>';markup+='<div class="clearfix">';markup+='<div class="left">Image <span id="busGalleryImageNo">'+(idx+1)+'</span> of '+urls.length+'</div>';markup+='<div class="right">Disclaimer: Photos shown above may not be of the scheduled bus</div>'
markup+='</div>'
return markup;}
function updateMarkup(){$('#busGalleryImage').html('<img src="'+urls[idx]+'">');$('#busGalleryImageNo').html(idx+1);$dialog.find('.prev, .next').css('visibility','visible');if(idx==0){$dialog.find('.prev').css('visibility','hidden');}
if(idx==n-1){$dialog.find('.next').css('visibility','hidden');}}}
function showDialog(u){$('<div />').qtip({content:{text:'<img src="/img/loader11.gif" style="display:block;margin:200px auto;"/>',title:{button:'Close'},ajax:{url:u}},position:{my:'center',at:'center',target:$(window)},show:{ready:true,modal:{on:true}},hide:false,style:'qtip-light qtip-dialog route-info-dialog',events:{hide:function(event,api){api.destroy();}}});}
function showFilterAppliedMsg(){var totalResults=oTable.fnSettings().fnRecordsTotal();var filteredResults=oTable.fnSettings().fnRecordsDisplay();var msg="Filters applied - "+filteredResults+"/"+totalResults+" results";ty.utils.showStickyNotification(msg);}
function initOperatorFilter(){var $f=$('.filter-content .filter-options.operator'),$allOpEl=$f.find('input[name=allOperators]');$.fn.dataTableExt.afnFiltering.push(function(oSettings,aData,iDataIndex){var opName=aData[0];if($allOpEl.is(':checked')||$f.find('input[value="'+opName+'"]').is(':checked')){return true;}else{return false;}});$f.find('input[type=checkbox]').on('change',function(e){var $this=$(this),$btn=$('#operatorFilterBtn'),$btnTxt=$('#operatorFilterBtn').find('strong');if($this.attr('name')=="allOperators"&&$this.is(':checked')){$f.find('.col input[type=checkbox]').each(function(){var p=$(this).prop('checked',false);$.uniform.update(p);$btn.removeClass('applied');$btnTxt.text('ALL OPERATORS');});}else{var p=$f.find('input[name=allOperators]').prop('checked',false);$.uniform.update(p);var $sel=$f.find('input[type=checkbox]:checked');if($sel.length==0){$f.find('input[name=allOperators]').click();var p=$f.find('input[name=allOperators]').prop('checked',true);$.uniform.update(p);$btn.removeClass('applied');$btnTxt.text('ALL OPERATORS');}else if($sel.length==1){$btn.addClass('applied');$btnTxt.text($sel.val().substr(0,30));}else{$btn.addClass('applied');$btnTxt.text('CUSTOM');}}
oTable.fnDraw();showFilterAppliedMsg();});}
function initBusTypeFilter(){var $f=$('.filter-content .filter-options.bus-type');$.fn.dataTableExt.afnFiltering.push(function(oSettings,aData,iDataIndex){var busSeating=$f.find('input[name=busSeating]:checked').val(),busAC=$f.find('input[name=busAC]:checked').val(),busClass=$f.find('input[name=busClass]:checked').val();if(busSeating=="seater"&&!routes[iDataIndex].HasSeater)return false;if(busSeating=="sleeper"&&!routes[iDataIndex].HasSleeper)return false;if(busAC=="AC"&&!routes[iDataIndex].HasAC)return false;if(busAC=="nonAC"&&!routes[iDataIndex].HasNAC)return false;if(busClass=="volvo"&&!routes[iDataIndex].IsVolvo)return false;if(busClass=="nonVolvo"&&routes[iDataIndex].IsVolvo)return false;return true;});$f.find('input[type=radio]').on('change',function(e){var busSeating=$f.find('input[name=busSeating]:checked').val(),busAC=$f.find('input[name=busAC]:checked').val(),busClass=$f.find('input[name=busClass]:checked').val(),$btn=$('#busTypeFilterBtn'),$btnTxt=$btn.find('strong');if(busSeating=="both"&&busAC=="both"&&busClass=="both"){$btn.removeClass('applied');$btnTxt.text('ALL TYPES');}else{$btn.addClass('applied');$btnTxt.text('CUSTOM');}
oTable.fnDraw();showFilterAppliedMsg();});}
function initDepartureFilter(){$.fn.dataTableExt.afnFiltering.push(function(oSettings,aData,iDataIndex){var $f=$('.filter-content .filter-options.departure'),isMorning=$f.find('input[name=timeSlot1]').is(':checked'),isNoon=$f.find('input[name=timeSlot2]').is(':checked'),isEvening=$f.find('input[name=timeSlot3]').is(':checked'),isNight=$f.find('input[name=timeSlot4]').is(':checked'),d=new Date(aData[2]),hour=d.getHours();if(!isMorning&&!isNoon&&!isEvening&&!isNight)return true;if(isMorning&&hour>=5&&hour<9)return true;if(isNoon&&hour>=9&&hour<17)return true;if(isEvening&&hour>=17&&hour<21)return true;if(isNight&&(hour>=21||hour<5))return true;return false;});$('.filter-content .filter-options.departure').find('input[type=checkbox]').on('change',function(e){var $f=$('.filter-content .filter-options.departure'),$sel=$f.find('input[type=checkbox]:checked'),$btn=$('#departureFilterBtn');if($sel.length==0||$sel.length==4){$btn.removeClass('applied');}else{$btn.addClass('applied');}
oTable.fnDraw();showFilterAppliedMsg();});}
function initPickupFilter(){var $f=$('.filter-content .filter-options.pickup'),$allPickupEl=$f.find('input[name=allPickups]');$.fn.dataTableExt.afnFiltering.push(function(oSettings,aData,iDataIndex){var rsId=routes[iDataIndex].RouteScheduleId;if($allPickupEl.is(':checked'))return true;if(pickupAreas[rsId]){for(var i=0;i<pickupAreas[rsId].length;i++){var areaId=pickupAreas[rsId][i];if($f.find('input[value="'+areaId+'"]').is(':checked')){return true;}}}
return false;});$f.find('input[type=checkbox]').on('change',function(e){var $this=$(this),$btn=$('#pickupFilterBtn');if($this.attr('name')=="allPickups"&&$this.is(':checked')){$f.find('.col input[type=checkbox]').each(function(){var p=$(this).prop('checked',false);$.uniform.update(p);$btn.removeClass('applied');});}else{var p=$f.find('input[name=allPickups]').prop('checked',false);$.uniform.update(p);var $sel=$f.find('input[type=checkbox]:checked');if($sel.length==0){$f.find('input[name=allPickups]').click();var p=$f.find('input[name=allPickups]').prop('checked',true);$.uniform.update(p);$btn.removeClass('applied');}else{$btn.addClass('applied');}}
oTable.fnDraw();showFilterAppliedMsg();});}
function initFareFilter(){$.fn.dataTableExt.afnFiltering.push(function(oSettings,aData,iDataIndex){var fare=parseInt(aData[7],10),fareRangeMin=parseInt($('.filter-content #fareRangeMin').text(),10),fareRangeMax=parseInt($('.filter-content #fareRangeMax').text(),10);return(fare>=fareRangeMin&&fare<=fareRangeMax);});}
function initFareSlider(){var fareRange=getFareRange();$('.filter-content #fareMin').html('<span class="WebRupee">Rs</span> '+fareRange.min);$('.filter-content #fareMax').html('<span class="WebRupee">Rs</span> '+fareRange.max);$('.filter-content #fareRangeMin').text(fareRange.min);$('.filter-content #fareRangeMax').text(fareRange.max);$('.filter-content #fareRangeSlider').slider({range:true,min:fareRange.min,max:fareRange.max,values:[fareRange.min,fareRange.max],slide:function(event,ui){$('.filter-content #fareRangeMin').text(ui.values[0]);$('.filter-content #fareRangeMax').text(ui.values[1]);},stop:function(event,ui){if(ui.values[0]==fareRange.min&&ui.values[1]==fareRange.max){$('#fareFilterBtn').removeClass('applied');$('#fareFilterBtn strong').html('ALL FARES');}else{$('#fareFilterBtn').addClass('applied');$('#fareFilterBtn strong').html('<span class="WebRupee">Rs</span> '+ui.values[0]+' - <span class="WebRupee">Rs</span> '+ui.values[1]);}
oTable.fnDraw();showFilterAppliedMsg();}});}
function formatFare(fare){return'<span class="WebRupee">Rs</span> '+fare;}
function updateRouteInfo($rowEl,seats,oFares,minFare,oDiscount,companyId){if(companyId==3930){if(seats>20)seats=20;}
$rowEl.find('.seats').html(seats);var currFare=$rowEl.find('td.fare .amount').data('fare');var ret={};if(minFare&&minFare!=currFare){if(Math.round(minFare)>Math.round(currFare)){ret.msg="Oops! The fare has increased from <span class='WebRupee'>Rs</span> "+currFare+" to <span class='WebRupee'>Rs</span> "+minFare+".";ret.type="warning";}else if(Math.round(minFare)<Math.round(currFare)){ret.msg="Hurray! The fare has reduced from <span class='WebRupee'>Rs</span> "+currFare+" to <span class='WebRupee'>Rs</span> "+minFare+".";ret.type="success";}
$rowEl.find('td.fare .amount strong').html(formatFare(minFare));$rowEl.find('td.fare .amount').data('fare',minFare);}
if(isMultipleFare(oFares)){var fareinfo=getMultipleFareMarkup(oFares,oDiscount);$rowEl.find('td.fare .multi').data('fareinfo',fareinfo);}
return ret;}
function getRouteInfo(rsId){for(var i=0;i<routes.length;i++){if(rsId==routes[i].RouteScheduleId)return routes[i];}}
function initSeatsDisplay(){$searchResultsTable.delegate('button.select-seats','click',function(){var $this=$(this),companyId=$this.data('companyid'),rsId=$this.data('rsid'),journeyDate=$this.data('journeydate'),$tr;$tr=$this.closest('tr');if($tr.next('tr').hasClass('seatchart-wrapper')){$tr.next('tr').remove();}
var randId="tmp"+parseInt(Math.random()*1000000,10);var colspan=$tr.find('td').length;$tr.after('<tr class="seatchart-wrapper" style="display:none;"><td colspan="'+colspan+'"><div id="'+randId+'" class="seatchart-content"></div></td></tr>');var url='/api/resource/seatChartWithPickups?rsid='+rsId+'&journeyDate='+journeyDate;var $seatChartDiv=$('#'+randId);displaySeatChart(rsId,$tr,$this,$seatChartDiv,url,companyId,journeyDate);var action=fromCity+"-"+toCity;trackGAEvent('select_seats_v2',action,rsId,1);trackBeacon('search_v2','select_seats_v2',action,rsId);});}
function displaySeatChart(rsId,$resultRow,$btn,$seatChartDiv,url,companyId,journeyDate){$resultRow.addClass('active');$resultRow.find('.loadingBar').show();$.ajax({type:'GET',url:url,contentType:"application/json",dataType:'json',cache:false,success:function(response){if(response.success){var oData={chart:response.data.chart,pickups:response.data.pickups};var routeInfo=getRouteInfo(rsId);var oDiscount={'isValid':routeInfo.HasDiscountPolicy,'amount':routeInfo.DiscountAmt,'percent':routeInfo.DiscountPer};var oMsg=updateRouteInfo($resultRow,oData.chart.layout.availableSeats,oData.chart.fare,oData.chart.minFare,oDiscount,companyId);var apiUrl='/api/transaction/save/?ver=v2';if(ty.search.data.token){apiUrl+="&token="+ty.search.data.token;}
ty.SeatChart({leg:ty.search.data.leg,journeyDate:journeyDate,route:routeInfo,data:oData,apiUrl:apiUrl,chartEl:$seatChartDiv,maxSeatsLimit:maxSeatsLimit[companyId],seatDetails:onwardSeats,msg:oMsg});$seatChartDiv.hide();$seatChartDiv.slideDown('fast');scrollSelectedRow($resultRow);$seatChartDiv.find('.close-chart a').click(function(){hideSeatChart($seatChartDiv,$resultRow);});var action=fromCity+"-"+toCity;trackGAEvent('seatchart_success_v2',action,rsId,1);trackBeacon('search_v2','seatchart_success_v2',action,rsId);}else{showSeatChartError();var action=fromCity+"-"+toCity;trackGAEvent('seatchart_error_v2',action,rsId,1);trackBeacon('search_v2','seatchart_error_v2',action,rsId);}},error:function(response){showSeatChartError();var action=fromCity+"-"+toCity;trackGAEvent('seatchart_error_v2',action,rsId,1);trackBeacon('search_v2','seatchart_error_v2',action,rsId);},complete:function(){$resultRow.find('.loadingBar').hide();$resultRow.next('tr').show();}});function showSeatChartError(){var msg="Oops! For some reason we could not retrieve seat chart. Please check your network connection and";msg+='<a href="javascript:void(0);" class="retry">Retry Again</a>.';var markup=$('#seatChartAlertTmpl').html();$seatChartDiv.html(markup);ty.utils.showAlert($seatChartDiv,msg,"error");$seatChartDiv.find('.alert-messages .retry').click(function(){$btn.click();var action=fromCity+"-"+toCity;trackGAEvent('seatchart_error_retry_v2',action,rsId,1);});$seatChartDiv.find('.close-chart a').click(function(){hideSeatChart($seatChartDiv,$resultRow);var action=fromCity+"-"+toCity;trackGAEvent('seatchart_error_close_v2',action,rsId,1);});}}
function scrollSelectedRow($resultRow){$('html,body').animate({scrollTop:$resultRow.offset().top-98},'slow');}
function hideSeatChart($seatChartDiv,$resultRow){$seatChartDiv.parents('tr').remove();$resultRow.removeClass('active');}
function initScrollHandler(){stickFilterArea();$(window).scroll(function(){stickFilterArea();});}
function stickFilterArea(){var st=$(window).scrollTop();if(st>=STICKY_HEIGHT){$('#searchInfo').css("position","fixed").css("top","0px").css("z-index","30").css("width","100%");$searchResultsTable.find('thead').css("position","fixed").css("top","31px").css("z-index","29").css("width","960px");$('.strip-table-hdbg').addClass('fixed');$('.white-strip-bg').css("display","block");$('.dataTables_wrapper').css("margin-top","107px");repositionFilters();}else{$('#searchInfo').css("position","inherit");$searchResultsTable.find('thead').css("position","inherit");$('.strip-table-hdbg').removeClass('fixed');$('.white-strip-bg').css("display","none");$('.dataTables_wrapper').css("margin-top","0px");repositionFilters();}}};;ty=window.ty||{};ty.SeatChart=function(o){var leg=o.leg,journeyDate=o.journeyDate,routeInfo=o.route,oData=o.data,apiUrl=o.apiUrl,$chartEl=o.chartEl,MAX_SEATS_LIMIT=o.maxSeatsLimit,seatDetails=o.seatDetails,oMsg=o.msg,checkoutData=o.checkoutData,fnCallback=o.callback,retryCounter=o.retryCounter;var oChart=oData.chart,unitWidth=30,unitHeight=30,minHeight=4*unitHeight,seatsArr,femaleReservedSeats=[],seatInfo={},KSRTC_ID=6933,VRL_ID=8684,CHILD_AGE=11,sawValidationError=0;init();function init(){initData();initDraw();initMessages();initSeatChart();initSeatSelection();initPickupPoints();initChartValidation();initChildFare();}
function initMessages(){if(oMsg&&oMsg.msg){ty.utils.showAlert($chartEl,oMsg.msg,oMsg.type);}
if(oChart.layout.availableSeats==0){chartSoldOut();var msg="Uh Oh! All the seats have been sold out. Please select another bus.";ty.utils.showAlert($chartEl,msg,"error");}}
function initData(){var layout=oChart.layout;seatsArr=[];for(var i=0;i<layout.lowerDeck.seatChart.length;i++){var seat=layout.lowerDeck.seatChart[i];seatsArr.push(seat);seatInfo[seat.SeatNo]={fare:seat.Fare,childFare:seat.ChildFare,isSleeper:seat.IsSleeper,isAC:seat.IsAC};}
if(layout.upperDeck){for(i=0;i<layout.upperDeck.seatChart.length;i++){var seat=layout.upperDeck.seatChart[i];seatsArr.push(seat);seatInfo[seat.SeatNo]={fare:seat.Fare,childFare:seat.ChildFare,isSleeper:seat.IsSleeper,isAC:seat.IsAC};}}}
function initDraw(){$chartEl.html(getInitialMarkup);}
function initSeatChart(){var $lowerDeck=$chartEl.find(".seatchart .lower-deck"),$upperDeck=$chartEl.find(".seatchart .upper-deck");var layout=oChart.layout;var lowerBound=drawSeatChart($lowerDeck,layout.lowerDeck.seatChart,layout.lowerDeck.hasCompartments);if(lowerBound.maxBottom<minHeight){lowerBound.maxBottom=minHeight;}
$lowerDeck.height(lowerBound.maxBottom);$lowerDeck.width(lowerBound.maxRight);var decksWrapperWidth=$lowerDeck.width()+52;if(layout.upperDeck){var upperBound=drawSeatChart($upperDeck,layout.upperDeck.seatChart,layout.upperDeck.hasCompartments);if(upperBound.maxBottom<minHeight){upperBound.maxBottom=minHeight;}
if(lowerBound.maxBottom>upperBound.maxBottom){upperBound.maxBottom=lowerBound.maxBottom;}else{lowerBound.maxBottom=upperBound.maxBottom;}
$upperDeck.height(upperBound.maxBottom);$upperDeck.width(upperBound.maxRight);$lowerDeck.height(lowerBound.maxBottom);$lowerDeck.width(lowerBound.maxRight);$upperDeck.show();decksWrapperWidth+=$upperDeck.width()+52+20;}
decksWrapperWidth=Math.min(decksWrapperWidth,920);$chartEl.find('.decks-wrapper').width(decksWrapperWidth);initSeatChartLegend();initSeatChartTooltip();}
function initSeatChartLegend(){$chartLegend=$chartEl.find('.seatchart-legend');if(!routeInfo.HasSeater){$chartLegend.find('.seater').hide();$chartLegend.css('width','642px');}
if(!routeInfo.HasSleeper){$chartLegend.find('.sleeper').hide();$chartLegend.css('width','506px');}}
function initSeatChartTooltip(){$chartEl.find('.deck a').qtip({content:{text:function(){var $this=$(this),seatNo=$this.data('seatno'),fare=$this.data('fare');if($this.hasClass('booked')){return"<strong>Seat Number: </strong>"+seatNo+"<br><strong>Booked</strong>";}else{return"<strong>Seat Number: </strong>"+seatNo+"<br><strong>Fare: </strong>"+fare;}}},style:{classes:'qtip-blue'},position:{my:'bottom center',at:'top center'}});}
function getInitialMarkup(){return $('#initialSeatChartTmpl').html();}
function chartSoldOut(){$chartEl.find('.pickup-points').hide();$chartEl.find('.pax-details').hide();$chartEl.find('.lastrow').hide();}
function drawSeatChart($el,seats,hasCompartments){var markup='',maxRight=0,maxBottom=0,topPadding=10,bottomPadding=10,extraWidth=0;for(var i=0;i<seats.length;i++){var seat=seats[i];if(seat.SeatNo){var row=seat.Row;var col=seat.Col;if(hasCompartments){row/=2;col/=2;}
if(hasCompartments&&i%2==0){markup+=addCompartmentWall(row,col,extraWidth)
extraWidth+=6;}
var classArr=["seat"];if(seat.IsAvailable){if(seat.Gender=='F'){classArr.push('female');femaleReservedSeats.push(seat.SeatNo);}else if(seat.Gender=='M'){classArr.push('male');}}else{classArr.push('booked');if(seat.Gender=='F'){classArr.push('female');}}
if(seat.IsSleeper){var className="w"+seat.Width+"h"+seat.Height;classArr.push(className);}
var cls=classArr.join(' ');var top=row*unitHeight+topPadding;var left=col*unitWidth+extraWidth;var style="top:"+top+"px; left:"+left+"px; position:absolute;";markup+='<div style="'+style+'">';markup+='<a href="javascript:void(0);" data-seatno="'+seat.SeatNo+'" data-fare="'+seat.Fare+'" class="'+cls+'"></a>';markup+='</div>'
if(hasCompartments&&i%2==1){extraWidth+=6;if(i==seats.length-1){markup+=addCompartmentWall(row,col+seat.Width/2,extraWidth)
left+=12;}}
var bottom=top+(unitHeight*seat.Height)+bottomPadding;var right=left+(unitWidth*seat.Width);maxBottom=Math.max(maxBottom,bottom);maxRight=Math.max(maxRight,right);}}
$el.find('.deck').html(markup);if(hasCompartments&&seats.length>=14){$el.addClass('too-long');}
return{"maxRight":maxRight,"maxBottom":maxBottom};}
function addCompartmentWall(row,col,extraWidth){var top=row*unitHeight;var left=col*unitWidth+extraWidth;var style="top:"+top+"px; left:"+left+"px; position:absolute;";return'<div style="'+style+'" class="compartment-wall"></div>';}
function highlightSection(x){if(x===1){$chartEl.find('.seatchart').addClass('active');}else if(x===2){$chartEl.find('.pickup-points').addClass('active');}else{$chartEl.find('.pax-details').addClass('active');}}
function unhighlightSection(x){if(x===1){$chartEl.find('.seatchart').removeClass('active');}else if(x===2){$chartEl.find('.pickup-points').removeClass('active');}else{$chartEl.find('.pax-details').removeClass('active');}}
function getInitialPaxDetails(){var ret=[];if(seatDetails){for(var seatNo in seatDetails){if(seatDetails.hasOwnProperty(seatNo)){var pax=seatDetails[seatNo];ret.push({name:pax.name,gender:pax.gender,age:pax.age});}}}
return ret;}
function initSeatSelection(){var $paxDetailsEl=$chartEl.find('.pax-details');var dummySeatNo='-';var dummyFare='-';var initalPax=getInitialPaxDetails();if(initalPax.length===0){addPaxDetailRow($paxDetailsEl,dummySeatNo,dummyFare);}else{for(var i=0;i<initalPax.length;i++){var pax=initalPax[i];addPaxDetailRow($paxDetailsEl,dummySeatNo,dummyFare,pax.name,pax.gender,pax.age);}}
$chartEl.find('.deck').delegate('a','click',function(){var $this=$(this);var totalFare=getTotalFare();if($this.hasClass('booked'))return;var seatNo=$this.data('seatno');if($this.hasClass('selected')){$this.removeClass('selected');var fare=removePaxDetailRow($paxDetailsEl,seatNo);totalFare-=fare;if(getNumOfSelectedSeats()==0){addPaxDetailRow($paxDetailsEl,dummySeatNo,dummyFare);if(!getPickupPoint()){unhighlightSection(2);unhighlightSection(3);}}}else{if(getNumOfSelectedSeats()==MAX_SEATS_LIMIT){$chartEl.find('.max-seats-msg').show();$chartEl.find('.max-seats-msg .num').html(MAX_SEATS_LIMIT);return;}
$this.addClass('selected');var fare=parseInt($this.data('fare'),10);addPaxDetailRow($paxDetailsEl,seatNo,fare);totalFare+=fare;highlightSection(2);}
setTotalFare(totalFare);});}
function getTotalFare(){var fare=$chartEl.find('.total').data('totalfare');return parseInt(fare,10);}
function setTotalFare(totalFare){var discount=getOperatorDiscount(totalFare);$chartEl.find('.total .amount').html(totalFare);$chartEl.find('.total').data('totalfare',totalFare);if(discount){$chartEl.find('.total .amount').addClass('strike');var newfare=totalFare-discount;var markup='<span class="reduced-fare">'+newfare+'</span>';markup+='<span class="discount"><span class="WebRupee">Rs </span>'+discount+' saved!</span>';$chartEl.find('.total .operator-discount-msg').html(markup)}else{$chartEl.find('.total .operator-discount-msg').html('');}}
function getOperatorDiscount(totalFare){if(routeInfo.HasDiscountPolicy){if(routeInfo.DiscountAmt){var totalSeats=getNumOfSelectedSeats();return totalSeats*routeInfo.DiscountAmt;}else{return Math.floor(totalFare*routeInfo.DiscountPer/100);}}else{return 0;}}
function getNumOfSelectedSeats(){return $chartEl.find('.deck .selected').length;}
function getSelectedSeats(){var ret=[];$chartEl.find('.pax-details .pax-detail-row').each(function(){var $this=$(this);var seatNo=$this.data('seatno');var gender=$this.find('select[name=paxGender]').val();ret.push({"SeatNo":seatNo,"Gender":gender});});return ret;}
function getEmptyPaxRow($paxDetailsEl){var elArr=$paxDetailsEl.find('.pax-detail-row');for(var i=0;i<elArr.length;i++){var $el=$(elArr[i]);if($el.data('seatno')=='-')return $el;}
return false;}
function addPaxDetailRow($paxDetailsEl,seatNo,fare,name,gender,age){var $rowEl=getEmptyPaxRow($paxDetailsEl);if(seatNo!='-'&&$rowEl){$rowEl.data('seatno',seatNo);$rowEl.data('fare',fare);$rowEl.find('select[name=paxGender]').data('seatno',seatNo);$rowEl.find('input[name=paxSeatNo]').val(seatNo);$rowEl.find('.seatno span').html(seatNo);$rowEl.find('.fare span').html(fare);}else{var rows=$paxDetailsEl.find('.pax-detail-row').length;var index=rows+1;var newRow=getPaxDetailMarkup(index,seatNo,fare);$paxDetailsEl.append(newRow.markup);$paxDetailsEl.find('select').uniform();$('.numeric').numeric(false);$rowEl=$('#'+newRow.id);$rowEl.find('input[name=paxName]').val(name);if(gender){$rowEl.find('select[name=paxGender]').val(gender);$rowEl.find('select[name=paxGender]').prev('span').text(gender);}
$rowEl.find('input[name=paxAge]').val(age);$paxDetailsEl.find('input, select').focus(function(){highlightSection(3);});}}
function removePaxDetailRow($paxDetailsEl,seatNo){var found=0;var fare=0;$paxDetailsEl.find('div.pax-detail-row').each(function(){var $this=$(this);if($this.data('seatno')==seatNo){found=1;fare=parseInt($this.data('fare'),10);$this.remove();}else{if(found){var index=$this.find('.index span').html();index=parseInt(index,10)-1;$this.find('.index span').html(index);}}});return fare;}
function getPaxDetailMarkup(index,seatNo,fare){var markup='';var id=ty.utils.getRandomId("paxRow");markup+='<div class="pax-detail-row row clearfix" data-seatno="'+seatNo+'" data-fare="'+fare+'"  id="'+id+'">';markup+='<div class="col index">';markup+='<span>'+index+'</span>';markup+='</div>';markup+='<div class="col name">';markup+='<input name="paxName" type="text" class="input textbox" id="'+ty.utils.getRandomId("paxName")+'" maxlength="50"/>';markup+='</div>';markup+='<div class="col gender">';markup+='<select name="paxGender" data-seatno="'+seatNo+'" id="'+ty.utils.getRandomId("paxGender")+'">';markup+='<option value="">--</option>';markup+='<option value="M">M</option>';markup+='<option value="F">F</option>';markup+='</select>';markup+='</div>';markup+='<div class="col age">';markup+='<input name="paxAge" type="text" class="input textbox numeric" id="'+ty.utils.getRandomId("paxAge")+'" maxlength="2"/>';markup+='</div>';markup+='<div class="col seatno">';markup+='<span>'+seatNo+'</span>';if(seatNo=='-'){markup+='<input type="hidden" name="paxSeatNo" value=""/>';}else{markup+='<input type="hidden" name="paxSeatNo" value="'+seatNo+'"/>';}
markup+='</div>';markup+='<div class="col fare">';markup+='<span>'+fare+'</span>';markup+='</div>';markup+='</div>';return{markup:markup,id:id};}
function initPickupPoints(){var $pickupEl=$chartEl.find('.pickup-points-list'),pickups=oData.pickups,address={};address[0]="";for(var i=0;i<pickups.length;i++){address[pickups[i].PickupId]=pickups[i].Address;}
$pickupEl.html(getPickupsMarkup(pickups));var $pickupSelEl=$pickupEl.find('select');$pickupSelEl.change(function(){var pickupId=$(this).val();if(pickupId){$pickupEl.find('.address').html(address[pickupId]);highlightSection(2);highlightSection(3);}else{$pickupEl.find('.address').html('');if(getNumOfSelectedSeats()==0){unhighlightSection(2);}
unhighlightSection(3);}});$pickupSelEl.focus(function(){highlightSection(2);}).blur(function(){if(!getPickupPoint()){unhighlightSection(2);}});}
function getPickupsMarkup(pickups){var markup='';markup+='<div class="row clearfix" id="'+ty.utils.getRandomId("pickups")+'">';markup+='<div class="left">';markup+='<select name="pickupPoint">';markup+='<option value="">-- Pickup points --</option>';for(var i=0;i<pickups.length;i++){var p=pickups[i];markup+='<option value="'+p.PickupId+'">'+p.PickupName+' | '+ty.utils.formatTime(p.PickupTS*1000)+'</option>';}
markup+='</select>';markup+='</div>';markup+='<div class="left address"></div>';markup+='</div>';return markup;}
function getPickupPoint(){return $chartEl.find('.pickup-points-list select').val();}
function isValidGender(seatNo,gender){for(var i=0;i<seatsArr.length;i++){if(seatsArr[i].SeatNo==seatNo&&seatsArr[i].Gender){return seatsArr[i].Gender==gender;}}
return true;}
function isFirstPax(paxRowId){var $firstPaxRowEl=$chartEl.find('.pax-detail-row').first();return $firstPaxRowEl.attr('id')===paxRowId;}
function initChartValidation(){var $form=$chartEl.find('form');$form.find('.submit button').click(function(event){event.stopPropagation();if(!$form.find('input[name=paxSeatNo]').valid()||!$form.valid()){sawValidationError=1;var action=ty.search.data.fromCity+"-"+ty.search.data.toCity;var rsId=routeInfo.RouteScheduleId;trackGAEvent('seatchart_validation_error_v2',action,rsId,1);trackBeacon('search_v2','seatchart_validation_error_v2',action,rsId);return false;}
if(routeInfo.CompanyId==VRL_ID){if(!femaleReservedSeatValidation()){alert("Females should book the reserved seats");return false;}}
submitChartForm($form);return false;});var validationRules={pickupPoint:{required:true},paxName:{required:true,alpha:true,rangelength:[3,50]},paxGender:{required:true,validGender:true},paxAge:{required:true,digits:true,range:[1,99],firstPaxAdult:true},paxSeatNo:{required:true}};var errorMessages={pickupPoint:{required:"Please choose a pickup point."},paxName:{required:"Passenger Name is required.",rangelength:"Name needs to be atleast 3 characters."},paxGender:{required:"Passenger Gender is required.",validGender:"Person with given gender is not allowed on this seat."},paxAge:{required:"Passenger Age is required.",digits:"Age seems to be invalid.",range:"Age seems to be invalid."},paxSeatNo:{required:"Select a seat by clicking on the seat chart above."}};$.validator.addMethod("validGender",function(value,element){var seatNo=$(element).data('seatno');return isValidGender(seatNo,value);},"Person with given gender is not allowed on this seat.");$.validator.addMethod("alpha",function(value,element){return this.optional(element)||value==value.match(/^[a-zA-Z .]+$/);},"Only alphabet, spaces and . characters are allowed.");$.validator.addMethod("firstPaxAdult",function(value,element){var paxRowId=$(element).parents('.pax-detail-row').attr('id');if(routeInfo.CompanyId==KSRTC_ID&&isFirstPax(paxRowId)&&value<=CHILD_AGE){return false;}else{return true;}},"First passenger should be atleast 12 years old.");var errorMap={};var validator=$chartEl.find('form').validate({rules:validationRules,messages:errorMessages,ignore:[],onsubmit:false,submitHandler:function(form){},errorPlacement:function(error,element){var $parent=getParentEl(element),parentId=$parent.attr('id'),elName=$(element).attr('name'),$errorEl=$parent.find('.error-element');addError(errorMap,parentId,elName,error.text());var errorString=getErrorsToDisplay(errorMap,parentId);if($errorEl.length){$errorEl.attr('title','<span></span>'+errorString);}else{$errorEl=$('<span class="error-element" title="<span></span>'+errorString+'"></span>');$parent.append($errorEl);$errorEl.qtip({style:{classes:'qtip-validator qtip-shadow',tip:{width:19,height:12}},position:{my:'left center',at:'right center'},show:{event:false,ready:true},hide:false});}
return true;},errorElement:"nothing",errorClass:"invalid",validClass:"success",highlight:function(element,errorClass,validClass){$(element).addClass(errorClass).removeClass(validClass);if($(element).prop('type')=='select-one'){$(element).prev().addClass(errorClass).removeClass(validClass);}},unhighlight:function(element,errorClass,validClass){$(element).removeClass(errorClass).addClass(validClass);if($(element).prop('type')=='select-one'){$(element).prev().removeClass(errorClass).addClass(validClass);}
var $parent=getParentEl(element),parentId=$parent.attr('id'),elName=$(element).attr('name'),$errorEl=$parent.find('.error-element');removeError(errorMap,parentId,elName);var errorString=getErrorsToDisplay(errorMap,parentId);if($errorEl.length){if(!errorString.length){$errorEl.remove();}else{$errorEl.attr('title','<span></span>'+errorString);}}}});}
function initChildFare(){if(routeInfo.CompanyId!=KSRTC_ID)return;$chartEl.find('.pax-details').on('blur','input[name=paxAge]',function(){var $this=$(this);var $paxRowEl=$this.parents('.pax-detail-row');var seatNo=$paxRowEl.data('seatno');var oldFare=parseInt($paxRowEl.data('fare'),10);var newFare;if($this.val()<=CHILD_AGE){newFare=seatInfo[seatNo].childFare;}else{newFare=seatInfo[seatNo].fare;}
if(oldFare!=newFare){var totalFare=getTotalFare();totalFare=totalFare-oldFare+newFare;$paxRowEl.data('fare',newFare);$paxRowEl.find('.fare span').html(newFare);setTotalFare(totalFare);}});}
function femaleReservedSeatValidation(){var selectedSeats=getSelectedSeats();if(hasEmptyFemaleReservedSeats(selectedSeats)){for(var i=0;i<selectedSeats.length;i++){if(selectedSeats[i].Gender=='F'&&isNextSeatEmpty(selectedSeats[i],selectedSeats)){return 0;}}}
return 1;}
function hasEmptyFemaleReservedSeats(selectedSeats){var used=0;for(var i=0;i<selectedSeats.length;i++){for(var j=0;j<femaleReservedSeats.length;j++){if(selectedSeats[i].SeatNo==femaleReservedSeats[j])used++;}}
return(used<femaleReservedSeats.length);}
function isNextSeatEmpty(seat,selectedSeats){for(var i=0;i<seatsArr.length;i++){if(seat.SeatNo==seatsArr[i].SeatNo){seat=seatsArr[i];break;}}
for(var i=0;i<seatsArr.length;i++){if(seat.SeatNo!=seatsArr[i].SeatNo&&!isSelectedSeat(seatsArr[i],selectedSeats)){if(seat.Deck==seatsArr[i].Deck){if(seat.Col==seatsArr[i].Col){if(seat.Row==seatsArr[i].Row-1||seat.Row==seatsArr[i].Row+1){if(seat.IsAvailable)return true;}}}}}
return false;}
function isSelectedSeat(seat,selectedSeats){for(var i=0;i<selectedSeats.length;i++){if(seat.SeatNo==selectedSeats[i].SeatNo)return true;}
return false;}
function addError(errorMap,id,name,error){errorMap[id]=errorMap[id]||{};errorMap[id][name]=error;}
function removeError(errorMap,id,name){if(errorMap.hasOwnProperty(id)){errorMap[id][name]="";}}
function getErrorsToDisplay(errorMap,id){var ret="";for(name in errorMap[id]){if(errorMap[id].hasOwnProperty(name)){var error=errorMap[id][name];if(error.length){return error;}}}
return ret;}
function getParentEl(element){return $(element).parents('.row');}
function submitChartForm($form){var postData=getPostData();showProgressBar();$.ajax({type:"POST",url:apiUrl,data:postData,dataType:"json",success:function(response){if(response.success){if(response.data&&response.data.redirectUrl){location.href=response.data.redirectUrl;}else if(response.data.pgFormData){fnCallback(response.data.pgFormData);}else{}}else{ty.co.handleHoldRetryResponse(response,retryCounter+1);}},error:function(response){},complete:function(){}});var action=ty.search.data.fromCity+"-"+ty.search.data.toCity;var rsId=routeInfo.RouteScheduleId;trackGAEvent('make_booking_v2',action,rsId,1);if(sawValidationError){if(!retryCounter){trackBeacon('search_v2','make_booking_x_v2',action,rsId);}else{trackBeacon('search_v2','make_booking_x_v2_retry',action,rsId);}}else{if(!retryCounter){trackBeacon('search_v2','make_booking_v2',action,rsId);}else{trackBeacon('search_v2','make_booking_v2_retry',action,rsId);}}
return false;}
function showProgressBar(){$chartEl.find('.submit button.submit-search').hide();$chartEl.find('.submit .loadingBar').show();}
function hideProgressBar(){$chartEl.find('.submit button.submit-search').show();$chartEl.find('.submit .loadingBar').hide();}
function getPostData(){var totalSeats=0;function getSeats(){var ret={},primary=1;$chartEl.find('.pax-details .pax-detail-row').each(function(){var $this=$(this);var seatNo=$this.data('seatno');var fare=$this.data('fare');var gender=$this.find('select[name=paxGender]').val();var name=$this.find('input[name=paxName]').val();var age=$this.find('input[name=paxAge]').val();ret[seatNo]={"seatNo":seatNo,"fare":fare,"isSleeper":seatInfo[seatNo].isSleeper,"isAC":seatInfo[seatNo].isAC,"gender":gender,"name":name,"age":age};if(primary){ret[seatNo]["primary"]=1;primary=0;}
totalSeats++;});return ret;}
function getPickup(){var pickups=oData.pickups;var selId=$chartEl.find('.pickup-points-list select').val();for(var i=0;i<pickups.length;i++){if(pickups[i].PickupId==selId)return pickups[i];}}
var o={};var tyquery=$.parseJSON(ty.search.data.query);var totalFare=getTotalFare();var operatorDiscount=getOperatorDiscount(totalFare);o.query={fromCityId:tyquery.FromCityId,fromCityName:tyquery.fromCityName,toCityId:tyquery.ToCityId,toCityName:tyquery.toCityName,mode:tyquery.mode,departDate:tyquery.JourneyDate,returnDate:tyquery.returnDate};var bookingInfo={journeyDate:journeyDate,route:routeInfo,pickup:getPickup(),seats:getSeats(),totalSeats:totalSeats,totalPrice:totalFare-operatorDiscount,operatorDiscount:operatorDiscount};o[leg]=bookingInfo;var ret={trip:JSON.stringify(o)};if(ty.search.data.token){ret.token=ty.search.data.token;}
if(checkoutData){ret.retry=retryCounter;for(var key in checkoutData){if(key!='trip'&&key!='retry'&&checkoutData.hasOwnProperty(key)){ret[key]=checkoutData[key];}}}
return ret;}
$.validator.prototype.checkForm=function(){this.prepareForm();for(var i=0,elements=(this.currentElements=this.elements());elements[i];i++){if(this.findByName(elements[i].name).length!=undefined&&this.findByName(elements[i].name).length>1){for(var cnt=0;cnt<this.findByName(elements[i].name).length;cnt++){this.check(this.findByName(elements[i].name)[cnt]);}}else{this.check(elements[i]);}}
return this.valid();}};;$(function(){function initModifySearch(){var $link=$('.modify-search a.link');var $el=$link.next('.modify-search-content');$('.modify-search a.link').click(function(){var $elContent=$el.find('.qtip-content');var right=ty.utils.getRightBound($link);$el.css('right',right);if($el.css('display')=='none'){if($elContent.html()==''){var content=$('#modifySearchTmpl').html();$('#modifySearchTmpl').remove();$elContent.html(content);ty.SearchWidget();}
showModifySearch();var action=ty.search.data.fromCity+"-"+ty.search.data.toCity;trackGAEvent('modify_search_v2',action,ty.search.data.journeyDate,1);}else{hideModifySearch();}});$('.modify-search .qtip-close').click(function(){hideModifySearch();});function hideModifySearch(){$el.hide();$link.removeClass('active');}
function showModifySearch(){$el.show();$el.focus();$link.addClass('active');}}
function initPrevNextLinks(){$('.prev-next-search-link').click(function(event){var $this=$(this);var href=$this.attr('href');var date=$this.data('date');if(href=='#'){return false;}else{$('#prgJourneyDate').html(date);$('#searchTableContent').hide();$('#searchProgress').show();var action=ty.search.data.fromCity+"-"+ty.search.data.toCity;if($this.hasClass('prev-day-link')){var evt='prev_day_v2';}else if($this.hasClass('next-day-link')){var evt='next_day_v2';}
trackGAEvent(evt,action,ty.search.data.journeyDate,1);}});}
function init(){initModifySearch();initPrevNextLinks();}
init();});